name: "Custom GitHub Action"
description: "A test GitHub Action"
#inputs:
#  dir_content:  # id of input
#    description: 'The content of the folder'
#    required: true
#    default: 'World'
runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fsspec
        pip install glob2
        pip install tqdm
        pip install nbformat
      shell: bash
    - name: Make readme
      working-directory: ./notebooks
      id: make_readme
      run: python make_readme.py
      shell: bash
    - name: Update Index Json
      working-directory: ./notebooks
      id: run_python_file
      run: python update_index_json.py
      shell: bash
    - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github_actions
          message: 'Commit README.md'
          add: 'README.md'
