name: "Make README.md and index.json"
description: "Makes README.md and index.json on push or pull request events for the "main" branch or when manually triggered"
runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install glob2
        pip install tqdm
        pip install nbformat
      shell: bash
    - name: Make README.md and index.json files
      working-directory: ./notebooks
      id: make_readme_and_index_files
      run: python make_readme.py
      shell: bash
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        message: Commit README.md
        committer_name: GitHub Actions
        committer_email: actions@github.com
        file_pattern: README.md index.json