name: 'Custom GitHub Action'
description: 'A test GitHub Action'
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Run Python Script
      id: run_python_file
      run: python src/update_index_json.py
      shell: bash
