name: Make README.md and index.json
on:
  # Triggers the workflow on push or pull request events
  push:
    branches:    
        - '**'        # matches every branch
        #- '!master'   # excludes master
    paths:
      - "**.ipynb"
      - "make_readme.py"
  pull_request:
    branches:    
          - '**'        # matches every branch
          #- '!master'   # excludes master
    paths:
      - "**.ipynb"
      - "make_readme.py"
  # Allows mannual triggering
  workflow_dispatch:
jobs:
  make-readme-and-index:
    runs-on: ubuntu-latest
    name: make readme.md and index.js job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run python script
        id: make_readme_and_index
        uses: ./
