name: Test Action
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - '**.ipynb'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.ipynb'
  workflow_dispatch:
jobs:
  run-python-action:
    runs-on: ubuntu-latest
    name: run python action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run custom python action 
        id: run_python_file
        uses: ./
