name: Make README and INDEX
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
    paths:
      - "**.ipynb"
      - "make_readme.py"
  pull_request:
    branches: ["main"]
    paths:
      - "**.ipynb"
      - "make_readme.py"
  # Allows mannual triggering
  workflow_dispatch:
jobs:
  make-readme-and-index:
    runs-on: ubuntu-latest
    name: make readme and index
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run python script
        id: make_readme_and_index
        uses: ./
