name: 'Update index json action'
description: "A github custom action"
run-name: ${{ github.actor }} is updating index.json
on:
  push:
    branches:
      - main
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  
    - name: Run the python file
      id: run_python_file
      run: python src/update_index_json.py
      shell: bash
